#!/usr/bin/env bash
set -e

git clone https://github.com/SpikeInterface/spikeinterface.git
cd spikeinterface
git checkout 9456e0577767311bd45363ad33e26ab76dca3188
pip install --no-cache-dir .[full]
cd ..
